### ISSUE TITLE
Refactor categories?

### ISSUE THREAD

**Issue by lemairecarl** [vitalab/vitalab.github.io#311]
Categories and tags have overlapping functionality... I guess we could use categories to determine the type of review, e.g.: Article review, Online course review, tutorial, tips & tricks, etc. Then, we would handle the rest with tags (domain, type of method, type of data, etc...)

(Not a critical issue)

**Comment by jhlegarreta** [comment]
IMHO, folders (or categories) should be kept as simple as possible. As said in #310, even if it is nice for oneself to have a folder where one could potentially put his/her reviews, that is hard to be generalizable.

Another reason for that is that, as you mention, we have tags, which facilitate finding articles on the public website.

Maintaining application-wise folders adds an extra overhead.

So to be honest, for the ones that we've created I'd let them as they are, but I'd not encourage to use, for example, `medical-imaging`.

But just an opinion.

**Comment by ppoulin91** [comment]
Agreed!

**Comment by lemairecarl** [comment]
I think the solution here is to keep the "course", "tutorial" and "blog" categories as they are, and put the contents of all the other categories into a new "article" category.

**Comment by jhlegarreta** [comment]
@lemairecarl's proposal sounds reasonable to avoid (dis)agreeing about the categories, etc.

**Comment by jodoin** [comment]
I agree with this.  Lets make a decision next week.

**Comment by jhlegarreta** [comment]
Following the decision we made, I'll refactor the categories whenever I find the time.

**Comment by jhlegarreta** [comment]
Finally addressed in #358.
