### ISSUE TITLE
Increase consistency in review post cross-references

### ISSUE THREAD

**Issue by jhlegarreta** [vitalab/vitalab.github.io#356]
Review post cross-references are not consistent across articles. At least three different forms have been used,:
1. `[ACNN](https://vitalab.github.io/article/2018/05/30/ACNN.html)`
e.g. in file [aadvSeg.md](https://github.com/vitalab/vitalab.github.io/blob/master/deep-learning/_posts/2018-06-16-advSeg.md).

2. `The model is a regular [ResNet]({{ site.baseurl }}{% post_url /deep-learning/2017-03-16-resnet %})`
e.g. in file [dilated_residual_network.md](https://github.com/vitalab/vitalab.github.io/blob/master/deep-learning/_posts/2017-08-02-dilated_residual_network.md).

3. `The generator is basically an [U-Net]({{ site.baseurl }}{% link deep-learning/_posts/2017-02-27-unet.md %}) which takes the label map as the input and produces an image.`
e.g. in [pix-2-pix.md](https://github.com/vitalab/vitalab.github.io/blob/master/deep-learning/_posts/2017-03-02-pix-2-pix.md)

A single criterion would make things more consistent and facilitate changes when needed.

**Comment by lemairecarl** [comment]
Jekyll's special syntax for internal links is impossible to remember, and has changed at some point. I think we should just use a plain old web link (first choice).

**Comment by jhlegarreta** [comment]
Thanks for the follow-up.

I think more elegant would be to use the third option, [according to the Jekyll documentation](https://jekyllrb.com/docs/liquid/tags/). This has the advantage that the user does not need to look on-line for the link, although the pattern is easy to remember. Even if our Jekyll version may be an older one, if it works for the example above, it should work for any other file unless we update our version and the new version changes its convention.

But just an opinion. If we think the plain link is better, I will change the instances to that solution.

**Comment by lemairecarl** [comment]
I'm ok with the 3rd option. But will people use it? That's the question. Maybe if there is an example in the howto, it would help.
So if you want to convert stuff and maybe add an example in the howto, you have my blessing.

**Comment by jhlegarreta** [comment]
We could change all existing ones to stick to the agreed form, and add a pre-commit check, but an example in the [`how-to`](https://github.com/vitalab/vitalab.github.io/blob/master/how-to.md) would be enough for the time being. The former require an amount of energy that we may not be willing to invest at this time.
