### ISSUE TITLE
Ensure that review articles have the correct yml header

### ISSUE THREAD

**Issue by jhlegarreta** [vitalab/vitalab.github.io#364]
Following a discussion with @lemairecarl, adding a script or a pre-commit hook to ensure that the review articles header follow the expected yml convetion/header could be useful.

At present, there may be some articles that are not rendered because some fields are missing.

**Comment by lemairecarl** [comment]
It would be nice, but I'm not willing to put time in this (other than review a solution).

**Comment by jhlegarreta** [comment]
I understand. We can leave it in the backlog until someone in the team is willing and has the time to tackle this. #365 and #369 were already a step towards this.
