### ISSUE TITLE
Better editing of tags

### ISSUE THREAD

**Issue by Dref360** [vitalab/vitalab.github.io#39]
When we edit the tags in how_to.md, it always causes conflict. We should rely on Jekyll data file and create the list at generation. This would help us editing tags in an easy way.

https://jekyllrb.com/docs/datafiles/

**Comment by lemairecarl** [comment]
Good idea. But since the list of tags changes rarely, I am not eager code this

**Comment by jodoin** [comment]
I kind of agree with carl.  Tags a changing now, but soon things will stabilize.  So lets keep it simple.
