### ISSUE TITLE
Add commit hook instructions in the How-to

### ISSUE THREAD

**Issue by lemairecarl** [vitalab/vitalab.github.io#417]
I just noticed I don't have the hooks, and that new users might not have them.

@jhlegarreta could you add the instructions please?

**Comment by jhlegarreta** [comment]
@lemairecarl the hooks are in the [utils folder](https://github.com/vitalab/vitalab.github.io/tree/master/utils), and the [how-to document](https://github.com/vitalab/vitalab.github.io/blob/master/how-to.md) explains how to set them up.

**Comment by lemairecarl** [comment]
Sorry! Read too fast
